config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth'}

  resources :home
  resources :schedules
  resources :teachers do
    resources :schedules
  end
  resources :students
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/provider.rb
class Provider < ApplicationRecord
  belongs_to :user
  serialize :hash
  validates :name, uniqueness: {scope: [:user_id] }
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  belongs_to :teacher, :class_name => "User", :foreign_key => "teacher_id"
  belongs_to :student, :class_name => "User", :foreign_key => "student_id"
  validates_presence_of :schedule_date
end

app/models/student.rb
class Student < User
  has_many :schedules
  has_many :teachers, through: :schedules
end

app/models/teacher.rb
class Teacher < User
  has_many :schedules
  has_many :students, through: :schedules
end

app/models/undefined_user.rb
class UndefinedUser < User

end

app/models/user.rb
class User < ApplicationRecord

  has_many :providers
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,:omniauthable, omniauth_providers: [ :google_oauth2, :twitter, :github, :linkedin, :facebook]

  Roles = ["Teacher", "Student"]

  def full_name
    "#{first_name&.capitalize} #{last_name&.capitalize}"
  end

  def teacher?
    type == "Teacher"
  end

  def student?
    type == "Student"
  end

  def undefined?
    type == "UndefinedUser"
  end

  def self.create_from_provider_data(provider_data)
    email = provider_data.info.email
    first_name = provider_data.info.name.split(' ')[0]
    last_name = provider_data.info.name.split(' ')[1]
    password = "111111"
    self.create(email: email, password: password,first_name: first_name,last_name: last_name,type: "UndefinedUser")
  end

  def devise_mapping
    Devise.mappings[:user]
  end

  def resource_name
    devise_mapping.name
  end

  def resource_class
    devise_mapping.to
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    before_action :valid_user

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :type])
        devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :type])
    end

    def after_sign_in_path_for(user)
        if user.student?
            schedules_path
        elsif user.teacher?
            students_path
        else
            edit_user_registration_path
        end
    end

    def valid_user
        if current_user && current_user.undefined?
            redirect_to edit_user_registration_path && return
        end
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  def index
    if current_user.undefined?
      redirect_to edit_user_registration_path
    end
  end
end

app/controllers/omniauth_controller.rb
class OmniauthController < ApplicationController

  def google_oauth2
    redirect
  end

  def twitter
    redirect
  end

  def github
    redirect
  end

  def linkedin
    redirect
  end

  def facebook
    redirect
  end

  def failure
    redirect_to new_user_registration_url, error: 'There is a problem signing you in'
  end

  private

  def auth_hash
    request.env['omniauth.auth']
  end

  def redirect
    if registered_user.present?
      if user_signed_in?
        if user.student?
          schedules_path
        else
          students_path
        end
      else
        sign_in_and_redirect registered_user
      end
    else
      failure
    end
  end

  def registered_user
    user_hash = auth_hash.to_json
    email = auth_hash.info.email
    provider = Provider.find_by(uid: auth_hash.uid,name: auth_hash.provider)
    if provider.present?
      user = provider.user
    else
      if user_signed_in?
        current_user.providers.find_or_create_by(name: auth_hash.provider, uid: auth_hash.uid, auth_hash: user_hash, access_token: auth_hash.credentials.token, email: email)
      else
        available_user = User.find_by(email: email)
        user = available_user.present? ? available_user : User.create_from_provider_data(auth_hash)
        user.providers.find_or_create_by(name: auth_hash.provider, uid: auth_hash.uid, auth_hash: user_hash, access_token: auth_hash.credentials.token, email: email)
      end
    end
    user
  end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController

  before_action :authenticate_user!
  before_action :set_schedule, only: [:update, :destroy, :show, :edit]

  def index
    if current_user.undefined?
      redirect_to edit_user_registration_path
    else
      @schedules = current_user.schedules
    end
  end

  def show

  end

  def new
    @schedule = current_user.schedules.new
    @teacher = Teacher.find(params[:teacher_id])
  end

  def create
    @schedule = current_user.schedules.new(schedule_params)
    @teacher = Teacher.find(schedule_params[:teacher_id])
    if @schedule.save
      redirect_to schedules_path, notice: 'Your schedule has been fixed successfully'
    else
      render :new
    end
  end

  def edit

  end

  def update

  end

  def destroy
    if @schedule.destroy
      redirect_to schedules_path, notice: 'Your schedule has been removed successfully'
    end
  end

  private

  def schedule_params
    params.require(:schedule).permit(:schedule_date, :teacher_id)
  end

  def set_schedule
    @schedule = Schedule.find(params[:id])
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :authenticate_user!

  def index
    if current_user.undefined?
      redirect_to edit_user_registration_path
    else
      @students = current_user.students.uniq
    end
  end

  def show
    @student = Student.find(params[:id])
    @schedules = @student.schedules.where(teacher_id: current_user.id)
  end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :authenticate_user!

  def index  # index controller action
    if current_user.undefined?
      redirect_to edit_user_registration_path
    else
      @teachers = Teacher.all
    end
  end

  def show

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/home/index.html.erb
<h1>Welcome! This is the Home Page</h1>

app/views/layouts/_error_message.html.erb
<div class="container-fluid" id="error_msg">
    <% if object.errors.full_messages.any? %>
    <% object.errors.full_messages.each do |error_message| %>
      <p class="alert alert-danger"> <%= error_message if object.errors.full_messages.first == error_message %> </p>
    <% break end %>
  <% end %>
</div>

app/views/layouts/_navbar.html.erb
<% if logged %>
  <ul>
    <li><%= link_to 'Home', root_path, class: "active" %></li>
    <li><%= link_to 'My Schedules', schedules_path %>
      <% if current_user.teacher? %>
      <li><%= link_to 'My Students', students_path %>
    <% end %>
    <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
    <div class="user">
      <li><h5>Logged in as <%= current_user.full_name %></h5></li>
    </div>
  </ul>
<% else %>
  <ul>
    <li><%= link_to 'Home', root_path, class: "active" %></li>
    <li><%= link_to "Log in", new_user_session_path %></li>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Studs1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/navbar', logged: user_signed_in? %>
    <%= yield %>
  </body>
</html>

app/views/schedules/_index.html.erb
<td><%= @serial %></td>
<td>
  <% if current_user.student? %>
    <%= schedule.teacher.full_name %>
  <% else %>
    <%= schedule.student.full_name %>
  <% end %>
</td>
<td><%= schedule.schedule_date.strftime("%d %B, %Y, %A") %></td>
<td><%= link_to 'Remove Schedule', schedule_path(schedule), method: :delete, data: {confirm: 'Are you sure?'}  %></td>

app/views/schedules/index.html.erb
<h2>My Schedules</h2>
<% if current_user.student? %>
  <%= link_to 'Fix a schedule', teachers_path  %>
<% end %>
<table>
  <tr>
    <th> # </th>
    <th> Full name </th>
    <th> Schedule Date </th>
    <th> Action </th>
  </tr>
  <% if @schedules.present? %>
    <% @serial = 1 %>
    <% @schedules.each do |schedule| %>
      <tr> <%= render partial: 'index', locals: {schedule: schedule} %> </tr>
      <% @serial += 1  %>
    <% end %>
  <% end %>
</table>

app/views/schedules/new.html.erb
<h1>Schedules for <%= @teacher.full_name %></h1>

<%= form_for(@schedule, html: {autocomplete: 'off'}) do |schedule| %>

  <%= render partial: 'layouts/error_message', locals: {object: @schedule} %>
  <%= schedule.hidden_field :teacher_id, value: @teacher.id, class: "form-control" %>

  <div class="form-group">
    <%= schedule.label :schedule_date, class: "control-label" %>
    <%= schedule.date_field :schedule_date, class: "form-control", placeholder: "yyyy-mm-dd" %>
  </div>

  <br/>
  <div class="form-group">
    <%= schedule.submit 'Save', class: "btn btn-success" %> |
    <%= link_to "Back", :back, class: "btn btn-dark" %>
  </div>

<% end %>
</div>

app/views/students/_index.html.erb
<td><%= @serial %></td>
<td><%= student.full_name %></td>
<td><%= link_to 'View all schedules', student_path(student) %></td>

app/views/students/index.html.erb
<h2>Students</h2>
<table>
  <tr>
    <th> # </th>
    <th> Full name </th>
    <th> Action </th>
  </tr>
<% if @students.present? %>
  <% @serial = 1 %>
  <% @students.each do |student| %>
    <tr> <%= render partial: 'index', locals: {student: student} %> </tr>
    <% @serial += 1  %>
  <% end %>
<% end %>
</table>

app/views/students/show.html.erb
<h2><%= @student.full_name %> schedules</h2>
<table>
  <tr>
    <th> # </th>
    <th> Full name </th>
    <th> Schedule Date </th>
    <th> Action </th>
  </tr>
  <% if @schedules.present? %>
    <% @serial = 1 %>
    <% @schedules.each do |schedule| %>
      <tr> <%= render partial: 'schedules/index', locals: {schedule: schedule} %> </tr>
      <% @serial += 1  %>
    <% end %>
  <% end %>
</table>

app/views/teachers/_index.html.erb
<td><%= @serial %></td>
<td><%= teacher.full_name %></td>
<td><%= link_to 'Take Schedule', new_teacher_schedule_path(teacher) %></td>

app/views/teachers/index.html.erb
<h2>Teachers</h2>
<table>
  <tr>
    <th> # </th>
    <th> Full name </th>
    <th> Action </th>
  </tr>
<% if @teachers.present? %>
  <% @serial = 1 %>
  <% @teachers.each do |teacher| %>
    <tr> <%= render partial: 'index', locals: {teacher: teacher} %> </tr>
    <% @serial += 1  %>
  <% end %>
<% end %>
</table>